name: Continuous Delivery Workflow
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - run: yarn install
      - run: yarn run lint
      - run: yarn run type-check
      - run: yarn run test
      - run: yarn run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./public
