name: Continuous Delivery Workflow
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          yarn install
      - name: deploy
        run: |
          yarn run deploy
