name: Continuous Delivery Workflow
on:
  push:
    branches:
      - develop
  repository_dispatch:
    types: [blog-updated]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: npm ci
      - run: npm run lint

      - run: npm run build
        env:
          STORAGE_API_ENDPOINT: https://storage.googleapis.com
          STORAGE_ACCESS_KEY_ID: ${{ secrets.STORAGE_ACCESS_KEY_ID }}
          STORAGE_SECRET_ACCESS_KEY: ${{ secrets.STORAGE_SECRET_ACCESS_KEY }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          GCS_FILE_NAME: ${{ secrets.GCS_FILE_NAME }}

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
