name: Continuous Integration Workflow
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          npm install
      - name: lint
        run: |
          npm run lint
      - name: type-check
        run: |
          npm run type-check
      - name: test
        run: |
          npm run test
      - name: build
        run: |
          npm run build
