name: Continuous Delivery Workflow
on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [blog-updated]

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pnpm install
      - run: pnpm run lint
      - run: pnpm run test

      - run: pnpm run build
        env:
          STORAGE_API_ENDPOINT: https://storage.googleapis.com
          STORAGE_ACCESS_KEY_ID: ${{ secrets.STORAGE_ACCESS_KEY_ID }}
          STORAGE_SECRET_ACCESS_KEY: ${{ secrets.STORAGE_SECRET_ACCESS_KEY }}
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          GCS_FILE_NAME: ${{ secrets.GCS_FILE_NAME }}

      - name: deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
