name: Continuous Integration Workflow
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
          yarn install
      - name: lint
        run: |
          yarn run lint
      - name: type-check
        run: |
          yarn run type-check
      - name: test
        run: |
          yarn run test
      - name: build
        run: |
          yarn run build
