name: Continuous Integration Workflow
on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - name: install
        run: |
          npm ci
      - name: lint
        run: |
          npm run lint
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v0"
        with:
          workload_identity_provider: ${{ secrets.GC_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GC_SERVICE_ACCOUNT }}
      - name: build
        run: |
          npm run build
        env:
          GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
          GCS_FILE_NAME: ${{ secrets.GCS_FILE_NAME }}
